[package]
name = "cpubaker"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = " Simple program that turns every core to 100%"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.16.0"
